// NOTE: Please update src/config/earlyAccessFeatures.ts if users can get early access to the feature

export const featureFlagNames = [
  'REACT_APP_FEATURE_ADDRESS_COLUMN',
  'REACT_APP_FEATURE_ASSET_ADDRESS_COLUMN',
  'REACT_APP_FEATURE_BATTERY_MANAGEMENT',
  'REACT_APP_FEATURE_BATTERY_NOTIFICATION_LIST',
  'REACT_APP_FEATURE_BLUETOOTH_SENSORS_MANAGEMENT',
  'REACT_APP_FEATURE_COMPARTMENT_ON_OFF_MODE',
  'REACT_APP_FEATURE_DEVICE_COMMISSIONING_SENSOR_TIMESTAMPS',
  'REACT_APP_FEATURE_DEVICE_COMMISSIONING_SENSOR_BLE',
  'REACT_APP_FEATURE_FUEL_LEVEL',
  'REACT_APP_FEATURE_BATTERY_LEVEL',
  'REACT_APP_FEATURE_ASSET_OFFLINE',
  'REACT_APP_FEATURE_GEOFENCE_TMP_EVENT',
  'REACT_APP_FEATURE_HEALTH_STATUS',
  'REACT_APP_FEATURE_ROUTE_REPLAY_TAB',
  'REACT_APP_FEATURE_TEMPERATURE_CHART_AND_TABLE',
  'REACT_APP_FEATURE_LYNXFLT_7559_COMPARTMENTS_TOGGLE',
  'REACT_APP_FEATURE_WIRELESS_SENSORS_GENERATE_REPORT',
  'REACT_APP_FEATURE_PHYSICAL_ADDRESS',
  'REACT_APP_FEATURE_BULK_IMPORT_WIRELESS_SENSORS',
  'REACT_APP_FEATURE_BULK_COMMISSION_DEVICES',
] as const;

export type FeatureFlagType = (typeof featureFlagNames)[number];
